### ISSUE TITLE
Wings not showing correct folder 

### ISSUE THREAD

**Issue by camden-git** [pelican-dev/panel#126]
### Current Behavior

Wings always shows the root folder instead of the correct folder contents. 

![Screenshot from 2024-04-20 18-41-08](https://github.com/pelican-dev/panel/assets/64759244/f8c25f55-96ff-4616-9989-881b1e34ed98)

This has to be a wings issue because wings is receiving the correct path. 
![Screenshot from 2024-04-20 18-41-16](https://github.com/pelican-dev/panel/assets/64759244/2ebdebbc-a709-4eb2-8680-4f727645d395)

### Expected Behavior

Show show correct folder contents

### Steps to Reproduce

Open any folder 

### Panel Version

feature/fillament

### Wings Version

c55417c21295f2c0bc0c9c52e2d55ee102f5a71b

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by iamkubi** [comment]
Definitely a panel issue caused by changing the parameters passed to wings.  Probably caused by 11e6430d42e83e13d50d93263661d31ddd30f8ea.

**Comment by NeonSpectrum** [comment]
@iamkubi That commit should fix the issue since before we're using `GuzzleHttp\Client` but recently changed to `Illuminate\Support\Facades\Http` (https://github.com/pelican-dev/panel/commit/358ac96ac1419209d78df7fc604b8cce2851c4fc#diff-6f8055f2fd391a469dd0f4dca85676e9458c14222757c25612708f3a837a9b60L55) that's why we need to update the parameters.

**Comment by iamkubi** [comment]
Yep, this was probably only ever broken on old versions of the filament branch.  Works fine now.
