### ISSUE TITLE
Fix varchar(191) by replacing with 255

### ISSUE THREAD

**Issue by lancepioch** [pelican-dev/panel#135]
https://www.grouparoo.com/blog/varchar-191

https://stackoverflow.com/questions/43832166/laravel-5-4-specified-key-was-too-long-why-the-number-191

**Comment by Software-Noob** [comment]
https://laravel.com/docs/5.4/migrations#creating-indexes

The default was set to 191 and never updated/removed after minimum MySQL version was updated

https://github.com/pelican-dev/panel/blob/main/app/Providers/AppServiceProvider.php#L28
