### ISSUE TITLE
Sidebar Moving while Scrolling

### ISSUE THREAD

**Issue by DitIsVincentPM** [pelican-dev/panel#142]
### Current Behavior

Currently in admin side if you scroll it moves the sidebar up
![chrome_6FAFIYB6Bw](https://github.com/pelican-dev/panel/assets/69402451/a90b9ec7-6a32-48b2-ad9c-30e2c6923723)

### Expected Behavior

it should stay in place

### Steps to Reproduce

Scroll

### Panel Version

canary

### Wings Version

/

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by lancepioch** [comment]
Thanks, this has been resolved!
