### ISSUE TITLE
Remove backups when server is deleted

### ISSUE THREAD

**Issue by Boy132** [pelican-dev/panel#145]
ref https://github.com/pterodactyl/panel/issues/2564

Wings should remove all server backups when the server is deleted. Currently they are only deleted from the panel database but the actual backup files remain.

**Comment by Boy132** [comment]
> I have also observed that, even if the server is deleted, backups are still present in backup pre-set location (for me it's /var/lib/pterodactyl/backups).

Yes, that's exactly what this issue is about.
The server backups are deleted from the panel database but the actual backup files are not deleted.

**Comment by lancepioch** [comment]
When a server is being deleted, if it has backups at all, I feel like we should just ask if they want them deleted or not.

**Comment by iamkubi** [comment]
> When a server is being deleted, if it has backups at all, I feel like we should just ask if they want them deleted or not.

Seems reasonable.  We'd also want to add a parameter to the delete server API call for non-interactive use.

Discussed this some and it seems like the easiest way to implement this will be in wings.  As a bonus the plan is to put backups in per-server directories for easier identification.  This will make it easier for admins that elect not to delete backups when the server is deleted to clean them up later.

**Comment by MennoGamed** [comment]
> When a server is being deleted, if it has backups at all, I feel like we should just ask if they want them deleted or not.

I don't know if this is useful, especially with automated systems like WHMCS. In any case, there should be an option in the panel to choose whether you want to give these choices or not. Otherwise, WHMCS can delete a server nicely, but you will be permanently stuck with backup files.

**Comment by Technoguyfication** [comment]
Is deleting backups from S3 storage implemented yet? If not, I think this issue should be re-opened or another issue should be created to implement cleanup of S3 backups.

**Comment by filasik** [comment]
> Is deleting backups from S3 storage implemented yet? If not, I think this issue should be re-opened or another issue should be created to implement cleanup of S3 backups.

Agree with you. For new users It is not the wanted experience.

**Comment by rmartinoscar** [comment]
It is already implemented
https://github.com/pelican-dev/panel/blob/3d764a89f7e36c61814c43c1bb612e959f0efb48/app/Services/Backups/DeleteBackupService.php#L70-L86
