### ISSUE TITLE
Resources > List (Table) | Add Empty State Actions

### ISSUE THREAD

**Issue by lancepioch** [pelican-dev/panel#158]
For each Resource that has no records, we should have a description of why you would want to create that Resource, and a button to do that!

https://filamentphp.com/docs/3.x/tables/empty-state#adding-empty-state-actions

**Comment by notAreYouScared** [comment]
https://github.com/pelican-dev/panel/commit/51bb60c3b12ab5ad4095447d8cc868bd039444ac Closes this.
