### ISSUE TITLE
Your panel.tar.gz is missing!

### ISSUE THREAD

**Issue by mrdiploben** [pelican-dev/panel#19]
### Current Behavior

I'm trying to install yet you removed the panel! How not nice

### Expected Behavior

Uh no panel?

### Steps to Reproduce

Try to download the panel?

https://github.com/pelican-dev/panel/releases/latest/download/panel.tar.gz

### Panel Version

-1

### Wings Version

-1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Saturn745** [comment]
Pelican hasn't been released yet, hence there being no releases on the releases tab.

**Comment by notAreYouScared** [comment]
We do not have a public release, yet.
