### ISSUE TITLE
Revamp Roles and Permissions

### ISSUE THREAD

**Issue by lancepioch** [pelican-dev/panel#193]

**Comment by Poseidon281** [comment]
Do you mean [#190](https://github.com/pelican-dev/panel/issues/190) by this or does something else need to be done (aswell)

**Comment by timoschirmer** [comment]
Are there any plans to support SSO options via SAML/OIDC or any other way in this process?

**Comment by KeySC07** [comment]
> Are there any plans to support SSO options via SAML/OIDC or any other way in this process?

Might be best to ask for this in #385 as it is more relevant. 

I did ask for the option to create user's upon first sign-in, which could be used to build on what you are asking for.

**Comment by MCSHUBpanels** [comment]
**I would like to say a suggestion that I want some custom permission/ access to the panel**
_Unlike pterodactyl, when we make a person admin he / she got all the perms but I want him to have a specific access like my support staff , he / she gets access to see all the server only and system administrator gets access to eggs , nodes section and owner got all the access_
