### ISSUE TITLE
API Docs error

### ISSUE THREAD

**Issue by linoranzberger** [pelican-dev/panel#202]
### Current Behavior

The Update an existing node on the Panel endpoint returns an error

### Expected Behavior

An error occurs during the endpoint update of an existing node on the panel. 

API error:
{
  "errors": [
    {
      "code": "HttpException",
      "status": "419",
      "detail": "CSRF Token Mismatch".
    }
  ]
}

API documents error:
Cannot generate the request documentation: Calling a member function parameter() to null

### Steps to Reproduce

Go to the API documentation, go to "Application API for Admins" and then to the end point "Update an existing node on the Panel"

### Panel Version

Beta 1

### Wings Version

Beta 1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by lancepioch** [comment]
Thanks but this is expected!
