### ISSUE TITLE
Create Database Unexpected Error

### ISSUE THREAD

**Issue by crocosnipe** [pelican-dev/panel#203]
### Current Behavior

When I create a database on any server, i get the error "unexpected error"

### Expected Behavior

Database should be created normally

### Steps to Reproduce

1. Create a Server
2. Create a new Database on this server

### Panel Version

Beta

### Wings Version

Beta

### Games and/or Eggs Affected

python-generic

### Docker Image

python3.12

### Error Logs

```bash
https://pteropaste.com/4gm0/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
As a temp fix, if you edit the database host and re-enter the password it will work <3
