### ISSUE TITLE
wings still showing MIT license

### ISSUE THREAD

**Issue by pxlkng** [pelican-dev/panel#208]
### Current Behavior

When running wings (e.g. manually in debug mode), it still shows the following MIT license disclaimer in its banner through CLI:

```
This software is made available under the terms of the MIT license.
The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.
```

### Expected Behavior

Showing its new license, AGPL-3.0, instead of MIT.

### Steps to Reproduce

Run wings in debug mode:

`sudo wings --debug`

### Panel Version

-

### Wings Version

1.0.0-beta1

### Error Logs

```bash
wings CLI output

INFO: [May 13 00:11:38.086] writing log files to disk path=/var/log/pelican/wings.log

                     ____
__ Pelican _____/___/_______ _______ ______
\_____\    \/\/    /   /       /  __   /   ___/
   \___\          /   /   /   /  /_/  /___   /
        \___/\___/___/___/___/___    /______/
                            /_______/ 1.0.0-beta1

Copyright © 2018 - 2024 Dane Everitt & Contributors

Website:  https://pelican.dev
 Source:  https://github.com/pelican-dev/wings
License:  https://github.com/pelican-dev/wings/blob/develop/LICENSE

This software is made available under the terms of the MIT license.
The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

DEBUG: [May 13 00:11:38.086] running in debug mode
[...]
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by iamkubi** [comment]
Wings is still MIT licensed.
