### ISSUE TITLE
GB and GiB 

### ISSUE THREAD

**Issue by Boy132** [pelican-dev/panel#211]
Currently, [sometimes](https://github.com/pelican-dev/panel/blob/main/app/Filament/Resources/NodeResource/Pages/EditNode.php#L149) `GB`/ `MB` is used and [sometimes](https://github.com/pelican-dev/panel/blob/main/app/Filament/Resources/NodeResource/Pages/EditNode.php#L110) `GiB`/ `MiB`.
We should pick and use one. As a side note, Docker uses `GiB`/ `MiB`. So we might need to convert the values.

**Comment by lancepioch** [comment]
We should be using mebibytes and gibibytes
