### ISSUE TITLE
Cannot php artisan migrate --seed --force with mysql

### ISSUE THREAD

**Issue by fuzeblocks** [pelican-dev/panel#220]
### Current Behavior

Followed the guide + clean installation of a mysql server

### Expected Behavior

The database is migrating

### Steps to Reproduce

Simply install the panel, but choose MySQL as record type 

### Panel Version

v1.0.0-beta1

### Wings Version

1.11.11

### Games and/or Eggs Affected

Nothing

### Docker Image

Nothing

### Error Logs

```bash
could not find driver (Connection: mysql, SQL: select
   table_name as `name`, (data_length + index_length) a
  s `size`, table_comment as `comment`, engine as `engi
  ne`, table_collation as `collation` from information_
  schema.tables where table_schema = 'panel' and table_
  type in ('BASE TABLE', 'SYSTEM VERSIONED') order by t
  able_name)
In Connector.php line 65:
  could not find driver
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
You're missing php8.2-mysql or php8.3-mysql if you're using 8.3
