### ISSUE TITLE
database host string bugget  

### ISSUE THREAD

**Issue by kaiyga** [pelican-dev/panel#224]
### Current Behavior

Scary ghosting. A line is entered, it may not be erased, it may return to the input that was before, it may, on the contrary, erase what you wrote, etc.

https://github.com/pelican-dev/panel/assets/92279086/fc3fbaf1-be42-48d2-ac21-d8fbdf2f9298

### Expected Behavior

Normal input?!?!?

### Steps to Reproduce

admin/database-hosts/create

Write to stroke "Host"

### Panel Version

1.4.0

### Wings Version

-

### Games and/or Eggs Affected

Panel

### Docker Image

-

### Error Logs

```bash
-
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
This is expected behavior as we auto fill the ip/domain as the name. Maybe we can change it to update after you move to the next field

**Comment by notAreYouScared** [comment]
https://github.com/pelican-dev/panel/commit/e9dc6cd32c186b2bcdca71d43a45c3c617e20b9f addresses this.
