### ISSUE TITLE
Edit server page shows wrong docker image

### ISSUE THREAD

**Issue by matrix2113** [pelican-dev/panel#229]
### Current Behavior

Go to server and update egg version. Editing the docker image updates the image name instead of docker image link

### Expected Behavior

Update docker image from Python 3.8 => 3.10

### Steps to Reproduce

Install new server with 3.8 which shows 3.8 in the installation but 3.12 when viewing admin panel. If you try to modify the docker image for the python egg, it enables custom image and the Docker image turns into text.

### Panel Version

v1.0.0-beta1

### Wings Version

v1.0.0-beta1

### Games and/or Eggs Affected

Python

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
This logic is known broken, but thankyou for making an issue so it does not fall through the cracks
