### ISSUE TITLE
Add Node CPU resource allocations

### ISSUE THREAD

**Issue by iamkubi** [pelican-dev/panel#233]
Nodes should be able to define CPU resource allocations that are respected by the deployment service.  This would work the same as disk/memory where you can set a maximum amount of CPU that should be assignable to the node.  After this automated deployments using the deployment service would consider the node to be full if adding the new server would drive its allocated CPU time above the node's defined limit.

As best I can tell no work is required on the wings side for this.  Node models would need to be updated, total assigned CPU allocations per node would need to be calculated, and that allocated usage would be used by the deployment service to determine if a node can deploy a server.

**Comment by Mutex21** [comment]
Shouldn't this also be included in the simple calculation of the load of that node? The load is very important as well.

**Comment by iamkubi** [comment]
I honestly have no idea what you mean.  We don't have a "simple calculation of the load of that node".
