### ISSUE TITLE
Settings page does not work

### ISSUE THREAD

**Issue by NaysKutzu** [pelican-dev/panel#241]
### Current Behavior

The settings page does not work!

### Expected Behavior

It shall display a settings page so i can change the panel name and everything

### Steps to Reproduce

just go on panel.domain/admin/settings

### Panel Version

1.0.0-beta

### Wings Version

Not relevant

### Games and/or Eggs Affected

Not relevant

### Docker Image

Not relevant

### Error Logs

```bash
https://pteropaste.com/i6ff/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
This hasn't been implemented yet.
