### ISSUE TITLE
Manage Docker Container labels

### ISSUE THREAD

**Issue by lancepioch** [pelican-dev/panel#248]
### Discussed in https://github.com/pelican-dev/panel/discussions/11

<div type='discussions-op-text'>

<sup>Originally posted by **DaniDipp** April 12, 2024</sup>
I would like to see better management of the docker containers - especially being able to modify the container name, environment variables and labels.
The labels especially would be great for integration with my traefik reverse proxy.</div>

**Comment by iamkubi** [comment]
Container name and labels make sense.  Environment variables can already be managed through egg variables.

**Comment by iamkubi** [comment]
Labels work now.

```
kubi@pelican-dev:~/code/wings$ docker inspect -f "{{json .Config.Labels}}" 9896b3b9e423
{"ContainerType":"server_process","Service":"Pelican","author":"Michael Parker","ffff":"aa","maintainer":"parker@pterodactyl.io","org.opencontainers.image.licenses":"MIT","org.opencontainers.image.source":"https://github.com/pterodactyl/yolks"}
```

Container name is required to be unique so making it configurable would require some more API and UI work to handle conflicts.  The name is already set to the server UUID which is sufficient for identification, if not easily human readable.
