### ISSUE TITLE
Changing node settings does not change configuration tab

### ISSUE THREAD

**Issue by LilTrublMakr** [pelican-dev/panel#251]
### Current Behavior

When changing settings on a node, it does not change the text on the configuration tab that you would copy/paste in to `/etc/pelican/config.yml`.

### Expected Behavior

Changing node settings would automatically update the configuration tab. You have to refresh the page for the settings to be reflected.

### Steps to Reproduce

Change settings.
Save.
Click on Configuration tab.

### Panel Version

1.0.0-beta2

### Wings Version

1.0.0-beta2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
What settings are you changing?

**Comment by notAreYouScared** [comment]
They update, they just require a page refresh.

**Comment by LilTrublMakr** [comment]
Ah, in Ptero, when you click on the configuration tab, it counts as a page reload instead of a page update. This is why it is always correct in Ptero. 

I don't think that this should be dismissed though since I think it will cause problems in the future if someone needs to edit the configuration for a wings node in the future.

**Comment by notAreYouScared** [comment]
![chrome_vLtYCfNiBB](https://github.com/pelican-dev/panel/assets/1757840/cdabb82b-8c4b-43cd-9165-5bd29dd18966)
