### ISSUE TITLE
Mailgun doesn't work

### ISSUE THREAD

**Issue by hustender** [pelican-dev/panel#257]
### Current Behavior

I tried to link my Mailgun account with my panel to send emails like password reset. It shows that the email was sent successfully but no email arrives. I even checked the mailgun analytics to find out that no request was made by the panel. After I checked the error logs I got the error below.

### Expected Behavior

I was expecting to get an password reset email or an email request showing up inside the mailgun panel.

### Steps to Reproduce

Run `php artisan p:environment:mail` and fill out your mailgun information including the secret API key.
Check the .env for errors.
Request a password reset email on the login page.
Run `tail -n 150 /var/www/pelican/storage/logs/laravel-$(date +%F).log | nc pteropaste.com 99`

This is my .env:
![grafik](https://github.com/pelican-dev/panel/assets/147628890/9c7c582d-0e09-4627-88c0-0ec413f49c74)

### Panel Version

1.0.0-beta2

### Wings Version

1.0.0-beta2

### Error Logs

```bash
https://pteropaste.com/0611/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Make sure you created the queue worker service: https://pelican.dev/docs/panel/getting-started/#creating-queue-worker

**Comment by hustender** [comment]
> Make sure you created the queue worker service: https://pelican.dev/docs/panel/getting-started/#creating-queue-worker

Did that from the beginning on and still doesn't work

**Comment by Boy132** [comment]
Please run the following command and share the link again:
`tail -n 300 /var/www/pelican/storage/logs/laravel-2024-05-18.log | nc pteropaste.com 99`
(the logs you originally posted don't contain the actual error)
