### ISSUE TITLE
Connection Count / Player Count

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [pelican-dev/panel#263]
Now, I know this is a feature that would be kind of a neesh feature to add but i'm wondering if we can get a connection count on how many people access the port. Or a supported player count for certain games that support it.

**Comment by Boy132** [comment]
Yes, it's planned! [Most likely as a first party plugin.](https://github.com/pelican-dev/panel/discussions/123#discussioncomment-9402192)

**Comment by lancepioch** [comment]
@Boy132 is correct, thanks!

**Comment by ZEROPOINTBRUH** [comment]
I dont get it is it complete or its just discarded
