### ISSUE TITLE
Unexpected behavior when user changes password.

### ISSUE THREAD

**Issue by DEV-DIBSTER** [pelican-dev/panel#278]
### Current Behavior

Video Demonstration:

https://github.com/pelican-dev/panel/assets/76603072/708b4ea4-d5f8-477f-8db5-33d093a2099e

Written Description:

User goes to change their password.
User types their current password.
User types their new password twice.
User hits the change password button.
User is shown a 500 internal server error screen.
Reload will then display the login page.

### Expected Behavior

Video Demonstration:

https://github.com/pelican-dev/panel/assets/76603072/bf4f6bb2-a10a-4db1-a2a8-899c596ced55

Written Description:

User goes to change their password.
User types their current password.
User types their new password twice.
User hits the change password button.
User is automatically directed back to login page.

### Steps to Reproduce

https://github.com/pelican-dev/panel/assets/76603072/708b4ea4-d5f8-477f-8db5-33d093a2099e

### Panel Version

1.0.0-beta2

### Wings Version

v1.0.0-beta2

### Error Logs

```bash
https://paste.pelistuff.com/Q7rs
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Please provide panel logs.
`tail -n 150 /var/www/pelican/storage/logs/laravel-$(date +%F).log | nc pterpaste.com 99`

**Comment by notAreYouScared** [comment]
@Boy132 The redirect is broken

![image](https://github.com/pelican-dev/panel/assets/1757840/08d4a9bd-63f7-45fc-bf3e-95702a496ad3)
