### ISSUE TITLE
Different disk sizes

### ISSUE THREAD

**Issue by Bubbelwubbel** [pelican-dev/panel#281]
### Current Behavior

I made a backup, why is this smaller than the server disk if it is a backup?

![image](https://github.com/pelican-dev/panel/assets/65186341/8abcd56f-2661-4fea-8ea9-aec005b7a029)
![image](https://github.com/pelican-dev/panel/assets/65186341/be930f02-108d-478b-9457-6c214c4d9bc5)

### Expected Behavior

That the disk is the same

### Steps to Reproduce

Create a backup, see the difference

### Panel Version

1.0.0-beta2

### Wings Version

lastet

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Software-Noob** [comment]
The backup is compressed archive, which reduces the overall size, until it's decompressed. It's not a bug.

For questions or support, please utilize the Github Discussions or Discord server.
