### ISSUE TITLE
Unable to view installing server

### ISSUE THREAD

**Issue by andyondrya** [pelican-dev/panel#306]
### Current Behavior

Panel shows "We're having some trouble connecting to your server, please wait..."
server.3ae504b5.js:1 WebSocket is already in CLOSING or CLOSED state.
server.3ae504b5.js:1 WebSocket connection to 'wss://wings:8443/api/servers/c8e0051a/ws' failed:

### Expected Behavior

Able to view the server with no errors.

### Steps to Reproduce

Install a new server. Existing server don't have issue.

### Panel Version

1.0.0-beta2

### Wings Version

1.0.0-beta2

### Games and/or Eggs Affected

n/a

### Docker Image

n/a

### Error Logs

```bash
https://paste.pelistuff.com/64ZA
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by andyondrya** [comment]
Edit was to fix formatting issue, the two websocket errors were coming from dev console.

**Comment by Boy132** [comment]
This is not a bug, you have a [wings connection issue](https://pelican.dev/docs/troubleshooting#wings-connection-issues).

> I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

Please don't just blindly tick boxes...

**Comment by andyondrya** [comment]
Apologies, with the error logs, there's another issue because I have 15 existing servers that I can access through the panel. It's only new servers that I create. I can communicate with Wings and have tried regenerating the token & config.

**Comment by Boy132** [comment]
> Apologies, with the error logs, there's another issue because I have 15 existing servers that I can access through the panel. It's only new servers that I create. I can communicate with Wings and have tried regenerating the token & config.

Update to Beta3 and this issue will be fixed.

**Comment by andyondrya** [comment]
Fixed on beta3
