### ISSUE TITLE
Minecraft eggs problem.

### ISSUE THREAD

**Issue by JoanFont1212** [pelican-dev/panel#317]
### Current Behavior

The current behavior is that when you start any minecraft service instead of picking the primary allocation picks the default allocation (25565) for all the servers, so if you have 3 servers all will start with 25565 every time, even if you change that in the server.properties, goes again to 25565.

### Expected Behavior

The behavior expected is to mantain the primary port instead of every time you start the server puts 25565 instead of your primary port.

### Steps to Reproduce

Update to the last version.
Have a minecraft server and start it.

### Panel Version

1.0.0-beta3

### Wings Version

1.0.0-beta3

### Games and/or Eggs Affected

All the eggs from Minecraft

### Docker Image

All the versions of the docker image.

### Error Logs

```bash
There isn't a "error log" for that.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Can you post a screenshot of all three servers allocation tables? 

The table is at the bottom of the edit server page

**Comment by JoanFont1212** [comment]
The other two servers aren't accesible rn because aren't mine, i will show the server that is mine.
![image](https://github.com/pelican-dev/panel/assets/161775222/9bf02503-09fa-4044-be44-acaada71a40a)
As you can see, i have this ports and the 25516 is the primary.
Every time i open the server starts in 25565 because changes it in server.properties.

**Comment by JoanFont1212** [comment]
(You cannot see, but 25516 is the primary, sorry for that)

**Comment by JoanFont1212** [comment]
I have a better example, in the pterodactyl demo, you can see it in this screenshot.
![image](https://github.com/pelican-dev/panel/assets/161775222/1fa25b7e-d6bd-4a5f-bc23-bb2e9f7478cc)

**Comment by Software-Noob** [comment]
Can you share the egg that you are using? The egg parser should modify the properties file to utilize the primary port. Either the egg is modified or there's an issue with the egg configuration service

**Comment by notAreYouScared** [comment]
This is an issue with the panel not passing the right replace config to wings.

**Comment by JoanFont1212** [comment]
I'm using the default eggs for Minecraft.

**Comment by notAreYouScared** [comment]
We know about the issue, the fix is as follows. 

You can "fix" it yourself.

Open the egg you are using, go to Process Management and under Configuration Files replace every `server.build.default.port` with `server.allocations.default.port`.

![image](https://github.com/pelican-dev/panel/assets/1757840/8382a475-2bcb-4b31-b2eb-a83e0ddceccd)


Other values you might want to replace:
`server.build.default.port` -> `server.allocations.default.port`
`server.build.default.ip` -> `server.allocations.default.ip`
`server.build.memory` -> `server.build.memory_limit`
`server.build.env._____` -> `server.environment._____`
