### ISSUE TITLE
Node Limits are not enforced

### ISSUE THREAD

**Issue by RMartinOscar** [pelican-dev/panel#321]
### Current Behavior

You can create servers on a node eventhough it's full
it should according to #233

### Expected Behavior

You shouldn't be able to create servers on a full node

### Steps to Reproduce

None

### Panel Version

1.0.0-beta3

### Wings Version

1.0.0-beta3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by iamkubi** [comment]
I believe the node limits only apply to the API.  I'm fairly sure the admin panel has always ignored node utilization checks.

**Comment by Boy132** [comment]
Yes, it only applies to the api.
Manually creating servers was never restricted.

**Comment by RMartinOscar** [comment]
Ok i thought you wanted to enforce it even for manually created servers sorry.
