### ISSUE TITLE
Wings stuck on `fetching list of servers from API`

### ISSUE THREAD

**Issue by wdhdev** [pelican-dev/panel#346]
### Current Behavior

When booting Wings, it gets stuck on `fetching list of servers from API`.

Please note, my Pelican panel is behind Cloudflare proxy, however it was working before, and the IP has not changed. Panel is running on the regular HTTPS port `443` and Wings is running on `8443` as for Wings to be able to run behind CF Proxy.

### Expected Behavior

Wings to boot up successfully.

### Steps to Reproduce

I believe this might be an issue with CF proxy, but I'm not sure why it would as my Pelican panel is configured to bypass any WAF rules and such so it couldn't be Wings getting stuck on the browser integrity check.

### Panel Version

v1.0.0-beta4

### Wings Version

v1.0.0-beta3

### Error Logs

Wings logs: https://paste.pelistuff.com/ayJC

```sh
root@pelican:/var/www/pelican# systemctl status wings
● wings.service - Wings Daemon
     Loaded: loaded (/etc/systemd/system/wings.service; enabled; preset: enabled)
     Active: active (running) since Sat 2024-06-08 09:25:49 AWST; 3s ago
   Main PID: 149187 (wings)
      Tasks: 7 (limit: 4644)
     Memory: 10.7M
        CPU: 33ms
     CGroup: /system.slice/wings.service
             └─149187 /usr/local/bin/wings

Jun 08 09:25:49 pelican.wdh.gg wings[149187]:  Source:  https://github.com/pelican-dev/wings
Jun 08 09:25:49 pelican.wdh.gg wings[149187]: License:  https://github.com/pelican-dev/wings/blob/main/LICENSE
Jun 08 09:25:49 pelican.wdh.gg wings[149187]: This software is made available under the terms of the MIT license.
Jun 08 09:25:49 pelican.wdh.gg wings[149187]: The above copyright notice and this permission notice shall be included
Jun 08 09:25:49 pelican.wdh.gg wings[149187]: in all copies or substantial portions of the Software.
Jun 08 09:25:49 pelican.wdh.gg wings[149187]:  INFO: [Jun  8 09:25:49.168] loading configuration from file config_file=/etc/pelican/config.yml
Jun 08 09:25:49 pelican.wdh.gg wings[149187]:  INFO: [Jun  8 09:25:49.179] configured wings with system timezone timezone=Australia/Perth
Jun 08 09:25:49 pelican.wdh.gg wings[149187]:  INFO: [Jun  8 09:25:49.180] checking for pelican system user username=pelican
Jun 08 09:25:49 pelican.wdh.gg wings[149187]:  INFO: [Jun  8 09:25:49.180] configured system user successfully gid=994 uid=999 username=pelican
Jun 08 09:25:49 pelican.wdh.gg wings[149187]:  INFO: [Jun  8 09:25:49.182] fetching list of servers from API
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by wdhdev** [comment]
After looking through the logs on [paste.pelistuff.com/ayJC](https://paste.pelistuff.com/ayJC), it seems to be fetching the IP directly even though Pelican is setup on an FQDN (pelican.wdh.gg).

**Comment by notAreYouScared** [comment]
Nothing was changed in that logic.....

i/o timeout (Client.Timeout exceeded while awaiting headers)

From the looks of it, wings can't access the panel.

**Comment by wdhdev** [comment]
`IP:443` doesn't seem to work, however `FQDN:443` does and Wings is fetching `IP:443`.

**Comment by Boy132** [comment]
That sounds like a nat problem. You should visit the Discord.

>  I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

Also, please don't just mindlessly check boxes...

**Comment by wdhdev** [comment]
Thanks, I might try reinstall and not use CF proxy. Sorry about the checkbox, I’ll ensure I check them properly next time.
