### ISSUE TITLE
MariaDB fixes

### ISSUE THREAD

**Issue by Im-0xC7** [pelican-dev/panel#347]
1. MariaDB is not listed as an option while setting up the database (`php artisan p:environment:database`), though setting up with the `mysql` option and changing `mysql` to `mariadb` in the .env file works fine
2. The getting started docs note that the minimum version required for MariaDB is 10.3, but the database uses the UUID data type which wasn't introduced until 10.7

Tested on panel v1.0.0-beta4

**Comment by Boy132** [comment]
1. The `mysql` works for both mysql and mariadb.
2. We don't use the uuid data type. All uuid columns are `char(36)`

**Comment by Im-0xC7** [comment]
> 1. The `mysql` driver works for both mysql and mariadb.

If I don't have a MySQL client installed I cannot use the `mysql` type, so changing `mysql` to `mariadb` in the .env allows me to use a MariaDB client (Just tested, gives `mysql not found`)

> 2. We don't use the uuid data type. All uuid columns are `char(36)`

Migration `2022_05_28_135717_create_activity_logs_table` uses the `uuid` type for the `batch` column, so attempting to run `php artisan migrate --seed --force` fails on any version earlier than 10.7 (Tested with panel v1.0.0-beta5 and MariaDB 10.6)

**Comment by Boy132** [comment]
> If I don't have a MySQL client installed I cannot use the `mysql` type, so changing `mysql` to `mariadb` in the .env allows me to use a MariaDB client (Just tested, gives `mysql not found`)

I see. That is a known issue.

> Migration `2022_05_28_135717_create_activity_logs_table` uses the `uuid` type for the `batch` column, so attempting to run `php artisan migrate --seed --force` fails on any version earlier than 10.7 (Tested with panel v1.0.0-beta5 and MariaDB 10.6)

No, that is still not a `uuid` datatype on the database. It's just a short way of creating a `char(36)`.

**Comment by Im-0xC7** [comment]
> > Migration `2022_05_28_135717_create_activity_logs_table` uses the `uuid` type for the `batch` column, so attempting to run `php artisan migrate --seed --force` fails on any version earlier than 10.7 (Tested with panel v1.0.0-beta5 and MariaDB 10.6)
> 
> No, that is still not a `uuid` datatype on the database. It's just a short way of creating a `char(36)`.

Either way, MariaDB versions before 10.7 don't recognize the `uuid` type/alias (at least from my tests on 10.3 & 10.6), so attempting to run the migrations fails

**Comment by Boy132** [comment]
> > > Migration `2022_05_28_135717_create_activity_logs_table` uses the `uuid` type for the `batch` column, so attempting to run `php artisan migrate --seed --force` fails on any version earlier than 10.7 (Tested with panel v1.0.0-beta5 and MariaDB 10.6)
> > 
> > 
> > No, that is still not a `uuid` datatype on the database. It's just a short way of creating a `char(36)`.
> 
> Either way, MariaDB versions before 10.7 don't recognize the `uuid` type/alias (at least from my tests on 10.3 & 10.6), so attempting to run the migrations fails

It has to be something different. I'm using mariadb 10.5 just fine.
Please visit the Discord and open a support thread with some information, like mariadb version, os and the errors you are getting.
