### ISSUE TITLE
what's the differences between this and pterodactyl panel

### ISSUE THREAD

**Issue by playstation452** [pelican-dev/panel#357]
I see linke no difference and I feel like this is worst than pterodactyl

**Comment by iamkubi** [comment]
Not an appropriate use of Github issues.  Any questions can be directed to discord, or the FAQ at https://pelican.dev/faq

**Comment by RMartinOscar** [comment]
Hey you can check the [faq](https://pelican.dev/faq)
Please close this issue if you want more detail join the [discord](https://discord.gg/pelican-panel)
