### ISSUE TITLE
Implement new single Server State/Status display

### ISSUE THREAD

**Issue by ItsNeil17** [pelican-dev/panel#362]
We currently have 2 separate enums for server state and server status.
Server state refers to our own state such as reinstall, transfer, etc.
Server status refers to the docker container's status such as running, stopped, etc.

If the current server state exists, then show it. If it's empty, then we should show the current container status.

This also includes the labelling in the Edit Server page.

**Comment by lancepioch** [comment]
Locked to @ItsNeil17

**Comment by iamkubi** [comment]
I'm fairly certain this is intentional.  You don't want to have to query the docker status of the server every time you want to render a server in the UI.

**Comment by ItsNeil17** [comment]
I believe the PR above resolves this issue, if you had something else in mind about how you wanted me to solve this issue, kindly let me know and I'll do it.

Another way is we can store container status like we store server status in the servers column to not have to query wings every time the page loads.

**Comment by iamkubi** [comment]
Although the way the API represents the state could be improved, it is important for performance reasons not to combine these 2 fields.
