### ISSUE TITLE
[$25] S3 backup error

### ISSUE THREAD

**Issue by clabeuhtegrite** [pelican-dev/panel#371]
### Current Behavior

When i copy/paste my s3 config from ptero, i have the error in the paste. All argument are good in the pelican doc.

My config is the follow : 

APP_BACKUP_DRIVER=s3
AWS_DEFAULT_REGION='auto'
AWS_ACCESS_KEY_ID='XXXXX'
AWS_SECRET_ACCESS_KEY='XXXXXXXXXX'
AWS_BACKUPS_BUCKET='pelican-backups'
AWS_ENDPOINT='https://XXXXX.r2.cloudflarestorage.com'
AWS_SIGNATURE_VERSION='4' (TRIED WITH A #)
AWS_USE_PATH_STYLE_ENDPOINT=true
BACKUP_MAX_PART_SIZE=19737000 (TRIED WITH A #)

### Expected Behavior

The backup colmplete successfuly.

### Steps to Reproduce

Copy/paste a valid config s3 from ptero.

### Panel Version

Beta5

### Wings Version

Beta3

### Games and/or Eggs Affected

Bungee

### Error Logs

```bash
https://paste.pelistuff.com/dtRK
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Hey this should be a better feat in https://github.com/pelican-dev/wings/issues also i believe that @iamkubi didn't figure out how to use S3 "folders" but commited anyway so that might be it

**Comment by clabeuhtegrite** [comment]
Ok, i've create one here because the S3 config are in the panel config. I create an issue in the wings project.

**Comment by Boy132** [comment]
Since this is a wings sided problem I will close this.
See https://github.com/pelican-dev/wings/issues/26
