### ISSUE TITLE
Translations - dashboard.blade.php

### ISSUE THREAD

**Issue by ItsNeil17** [pelican-dev/panel#372]
### Current Behavior

Last section of the dashboard isn't translated
![image](https://github.com/pelican-dev/panel/assets/68216747/85152571-308b-4d58-a766-87bd5f6ae3a7)

https://github.com/pelican-dev/panel/blob/58bfa122802b7612e7a7de9df99d144a66083647/resources/views/filament/pages/dashboard.blade.php#L100-L102

### Expected Behavior

Translations to be done using crowdin

### Steps to Reproduce

N/A

### Panel Version

v1.0.0-beta5 (91844417)

### Wings Version

N/A

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
N/A
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Hey the resources folder is basically free of change atm we only edited the admin side

**Comment by Boy132** [comment]
Many parts are not translated yet.
Translation will be done later.

**Comment by ItsNeil17** [comment]
> Many parts are not translated yet. Translation will be done later.

I thought everything was translated because you guys allowed users to translate. My bad

**Comment by Poseidon281** [comment]
No some things have been translated, but as I understand it translations are really going to be finished when there is a stable release
