### ISSUE TITLE
Add Vite to allow custom Tailwind classes

### ISSUE THREAD

**Issue by lancepioch** [pelican-dev/panel#377]
This might not be compatible with yarn, so it might have to wait for #353 

Reference: https://medium.com/@halimdirgantara/setting-up-filament-panel-resources-with-tailwind-css-filament-series-part-3-aaed54b04d52

**Comment by ItsNeil17** [comment]
An official doc for this has also been publised, also, new projects made with Filament now actually do install vite by themselves. 

https://filamentphp.com/docs/3.x/actions/installation#installing-tailwind-css

**Comment by alexevladgabriel** [comment]
This should be solved with #493
