### ISSUE TITLE
Setting backup limit to negative value causes HTTP 500

### ISSUE THREAD

**Issue by kalsandbrook** [pelican-dev/panel#397]
### Current Behavior

When editing a server, setting it's backup limit to a negative value causes the panel to throw an Internal Server Error.

### Expected Behavior

Usually, setting a limit value to -1 implies the ability to create an unlimited number of backups.

### Steps to Reproduce

1. Edit a server
2. Set backup limit to a negative value
3. Press 'Save Changes'

### Panel Version

1.0.0-beta5

### Wings Version

1.0.0-beta5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
`-1` is not valid. `0` means unlimited backups.
But should look into the 500 error. Please post panel logs.
