### ISSUE TITLE
500 Edit Allocation

### ISSUE THREAD

**Issue by RMartinOscar** [pelican-dev/panel#400]
### Current Behavior

You get a 500 when setting an invalid ip while editing an already existing allocation

### Expected Behavior

Should cancel the change and display an error

### Steps to Reproduce

Edit allocation with invalid ip address

### Panel Version

canary (59bbb637) 

### Wings Version

1.0.0-beta3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Should be cool if you could only allocate ip address that are known to the host so you don't get *Cannot bind address*
>127.0.0.1
>pelican_nw gateway
>local ip

**Comment by lancepioch** [comment]
Replaced with #68
