### ISSUE TITLE
Cant select additional allocation when editing the server

### ISSUE THREAD

**Issue by wikitech24** [pelican-dev/panel#408]
### Current Behavior

When adding additional allocation to already created server. The port that you want to add is not searchable or not listed

Search is only showing first 50 free entries

Discord with my post: https://discord.com/channels/1218730176297439332/1251917031465418833

### Expected Behavior

Free Allocation should display when the search entity is mathing the free allocation
OR
It should be listed without search

### Steps to Reproduce

Have a node with lots of allocations (my node have over 1k+)
Edit a server you want to add additional allocation

Search for allocation that is at least 50 entries away. Example: 28000-28999, and search for 28082.

### Panel Version

1.0.0-beta5

### Wings Version

1.0.0-beta3

### Games and/or Eggs Affected

Rust

### Docker Image

ghcr.io/pterodactyl/games:rust

### Error Logs

```bash
Wings: https://paste.pelistuff.com/EtJ5
Panel: https://paste.pelistuff.com/cnC4
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by lancepioch** [comment]
Thanks, we are replacing allocations here: https://github.com/pelican-dev/panel/pull/395
