### ISSUE TITLE
Allocations can not be created with an ipv6 address

### ISSUE THREAD

**Issue by theoparis** [pelican-dev/panel#428]
### Current Behavior

![image](https://github.com/pelican-dev/panel/assets/11761863/f36f727d-f9bd-4121-997a-50d7760f9f3b)

The panel complains that it has to be an ipv4 address 😬 

### Expected Behavior

.

### Steps to Reproduce

Enter a ipv6 address in a node allocation 

### Panel Version

1.0.0-beta5

### Wings Version

v1.0.0-beta3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Hey will be fixed with PR #429

**Comment by lancepioch** [comment]
This is correct behavior. We do not support ipv6.

**Comment by RMartinOscar** [comment]
Should be _Not planed_ instead of _Completed_
