### ISSUE TITLE
[Eggs] `egg_variables` exist when egg is deleted

### ISSUE THREAD

**Issue by notAreYouScared** [pelican-dev/panel#436]
Create an egg with variables
Observe variables in the `egg_variables` table for the newly created egg
Delete newly created Egg
Observe variables in `egg_variables` table and see that the variables for the egg still exist. 

They should be removed when the egg is deleted. 

This was observed using SQLite

**Comment by Boy132** [comment]
Closing this in favor of #477. The foreign keys are missing.
