### ISSUE TITLE
Create Allocations | Notification Error

### ISSUE THREAD

**Issue by cesarmr-github** [pelican-dev/panel#452]
(I know you can't create ports lower than 1024, but it's a bug in the panel that doesn't give the alert.)

### Current Behavior

When you on a node try to create a port smaller than 1024, instead of giving an error, it gives a blank screen. And then when you reload the page you get the error, but with a bug in the title.

![image](https://github.com/pelican-dev/panel/assets/167689141/f85741ed-43b7-413c-9891-90497560586d)
When you do F5 ->
![image](https://github.com/pelican-dev/panel/assets/167689141/fcf0c083-0213-467f-a5cc-823989e9bc7e)

### Expected Behavior

That the error with the fixed title instead of a blank screenshot is given.

### Steps to Reproduce

Create a port lower than 1024
![image](https://github.com/pelican-dev/panel/assets/167689141/d5b49576-d6b3-4f85-a25c-f5a760001a62)

### Panel Version

1.0.0-beta6

### Wings Version

v1.0.0-beta3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
The proposed solution would be to filter the ports and remove them before they're passed to the creation service.
