### ISSUE TITLE
Servers can not be deleted via API as "Server has a Database"

### ISSUE THREAD

**Issue by ItzExotical** [pelican-dev/panel#453]
### Current Behavior

Just like we can't delete servers with databases in the frontend, the API is unable to. This causes problems when something like the WHMCS module has to terminate a service.

### Expected Behavior

The server should be successfully removed, maybe by passing some form of force delete property or something.

### Steps to Reproduce

1. Make a DELETE request to https://{{instance}}/api/application/servers/{{server_id}}
2. API returns response:
```
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => QueryException
                    [status] => 500
                    [detail] => An unexpected error was encountered while processing this request, please try again.
                )

        )

    [status_code] => 500
)
```

### Panel Version

1.0.0-beta6

### Wings Version

1.0.0-beta3

### Games and/or Eggs Affected

All

### Docker Image

All

### Error Logs

```bash
Can't seem to find any panel error logs for today's date.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Just tried it out, for the front end just need to remove the check for the api i didn't have any issue, are you sure that you are using latest version ?

**Comment by ItzExotical** [comment]
> Just tried it out, for the front end just need to remove the check and for the api i didn't have any issue, are you sure that you are using latest version ?

Yep, I am.
"You are currently using 1.0.0-beta6. Your panel is up-to-date!"
Not sure why it does not want to be deleted then.

**Comment by ItzExotical** [comment]
Issue solved! The database host user details had been changed for some reason. Works now.
