### ISSUE TITLE
Unknown Node allocated cpu, ram, disk

### ISSUE THREAD

**Issue by RMartinOscar** [pelican-dev/panel#498]
### Current Behavior

Those vars are never updated due to [e634dd8](https://github.com/pelican-dev/panel/commit/e634dd81b1ff45102d65c6a58f26a1fdd7024e59#diff-a4edc5f1b41c92e105baab86f8c39c1787d3875a315a1c2503d4493af530d750) & [50fa260](https://github.com/pelican-dev/panel/commit/50fa260a382a52ae6c668dc4b798b5f940a0019e#diff-a4edc5f1b41c92e105baab86f8c39c1787d3875a315a1c2503d4493af530d750R38) so we don't have any way of summing allocated resources which is really annoying when you want to use Limits (should be done whenever we create/update a server to avoid flooding querys)
https://github.com/pelican-dev/panel/blob/56b4938dc2b3b38dc731d929e37c869f0c21ab4b/app/Models/Node.php#L137-L139

### Expected Behavior

Those variables should represent the sum of resources allocated to servers on this node

### Steps to Reproduce

None, i just tried to duplicate https://github.com/pelican-dev/panel/pull/459 but for allocated resources and not the ones being in use atm

### Panel Version

1.0.0-beta6

### Wings Version

1.0.0-beta3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This is intented. These variables are only used when checking if the node is viable.
https://github.com/pelican-dev/panel/blob/main/app/Services/Deployment/FindViableNodesService.php#L22-L25
https://github.com/pelican-dev/panel/blob/main/app/Models/Node.php#L245-L269

**Comment by RMartinOscar** [comment]
I know but we don't get any info on what's allocated then ?

**Comment by Boy132** [comment]
They aren't always 0?
![grafik](https://github.com/user-attachments/assets/02cc3a77-5b61-4be4-b999-5679411cc299)

**Comment by RMartinOscar** [comment]
Well i must have missed something because i was always getting 0 out of them until i redid the query

**Comment by Boy132** [comment]
Yes, because they are only filled when running that query. They are just temp variables for the query, basically.

**Comment by RMartinOscar** [comment]
I see well i'll sleep slightly less dumb sorry for the inconvenience
