### ISSUE TITLE
Mobile UI in server->eggs

### ISSUE THREAD

**Issue by Derbosik** [pelican-dev/panel#512]
### Current Behavior

https://demo.pelican.dev/admin/servers/1/edit?tab=-egg-tab contains a mobile overlapping glitch in the UI.
https://demo.pelican.dev/admin/settings?tab=-general-tab contains an overflow issue with selectors.

### Expected Behavior

Aligning the items properly.

### Steps to Reproduce

Visit the mentioned link on mobile.

### Panel Version

canary (demo panel version)

### Wings Version

canary (demo panel version)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Can you share screenshots of the first one? 

As for the overflow, that's a filament issue, I've reached out to them.

**Comment by Derbosik** [comment]
![Screenshot_2024-07-30-01-10-49-83_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/229ebbf7-e100-4016-bba0-80e1ae7596ab)
![Screenshot_2024-07-30-01-10-29-95_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/23ad95b0-23b0-49ec-8ce5-09e3d2fd948f)
![Screenshot_2024-07-30-01-10-02-82_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/e01b8542-0c8c-4535-862d-676cb0519fde)
