### ISSUE TITLE
[Admin Panel] Create server results in TextArea not found error.

### ISSUE THREAD

**Issue by ryzech** [pelican-dev/panel#516]
### Current Behavior

- Go to the admin panel
- Go to the server tab
- Click create server
- Error appears
![Screenshot from 2024-07-30 12-40-31](https://github.com/user-attachments/assets/ab571d57-4514-405e-af7f-beae60236675)

### Expected Behavior

- Go to the admin panel
- Go to the server tab
- Click create server
- Functions normally

### Steps to Reproduce

Be on the latest git commit, attempt to click the create server button, an error will appear.

### Panel Version

canary (d22f9756)

### Wings Version

1.0.0-beta3

### Error Logs

```bash
https://paste.pelistuff.com/3jaW
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Not able to reproduce this on the demo...

Created and Edited the same server just fine
![image](https://github.com/user-attachments/assets/725296d0-fe87-4c74-8593-64701fb217db)

**Comment by ryzech** [comment]
Looked into it myself, the issue seems to be that in `app/Filament/Resources/ServerResource/Pages/CreateServer.php` `Filament\Forms\Component\TextArea` is actually supposed to be `Filament\Forms\Component\Textarea` . But it only causes issues in some OS', while other's are fine due to case sensitivity.

**Comment by notAreYouScared** [comment]
Changed.... Everything else is CamelCase...

**Comment by ryzech** [comment]
Yeah, very weird, but it worked immediately after changing it
