### ISSUE TITLE
Personalized Favicon problem

### ISSUE THREAD

**Issue by GaspardG0001** [pelican-dev/panel#524]
### Current Behavior

- By default, the Favicon link is "./pelican.ico". As a result, the icon is not displayed. 
- The console part (outside admin interface) doesn't use the Favicon defined in settings but the default one (pelican.ico).

### Expected Behavior

- **By default, the Favicon link should be "/pelican.ico", allowing the icon to be displayed** (for simplicity's sake, the "/" should not be indicated). Only the file name should be displayed: "pelican.ico" for example).
- The non-admin interface should display the customized icon.

### Steps to Reproduce

**To reproduce the path problem :**
- Go to configuration page
**To reproduce the wrong display :**
- Go to the non-administrator area of the panel
- View the Favicon

### Panel Version

1.0.0-beta7

### Wings Version

1.0.0-beta3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
The front end is still compiled, therefor it will not change until the new client area is done. 

Does it change on the admin Area when you change it? What folder are you putting the ico in?

**Comment by Boy132** [comment]
Yes, the default path should be `/pelican.ico`, so without the `.`.
The favicon is only applied to filament pages, so only the new admin area.

**Comment by RMartinOscar** [comment]
https://github.com/pelican-dev/panel/pull/529
