### ISSUE TITLE
Error 500 /admin

### ISSUE THREAD

**Issue by Tealk** [pelican-dev/panel#525]
### Current Behavior

I tried to update to beta 7 today, now I get an error 500 when I try to call up the admin page.
https://pelican.dev/docs/panel/update

### Expected Behavior

https://pelican.dev/docs/panel/update

### Steps to Reproduce

Follow this: https://pelican.dev/docs/panel/update

### Panel Version

v1.0.0-beta7

### Wings Version

v1.0.0-beta3

### Error Logs

```bash
/laravel-2024-08-05.lo' for reading: No such file or directory
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by andyondrya** [comment]
No error logs? Did you look in the announcements channel with Charles' hotfix?

`rm /var/www/pelican/app/Filament/Clusters/Settings.php`

**Comment by Tealk** [comment]
> announcements channel

What kind of channel do you mean?

**Comment by andyondrya** [comment]
The announcements channel in the Pelican server. Look at this message link -> https://discord.com/channels/1218730176297439332/1218753783786639380/1269714875173703831

**Comment by andyondrya** [comment]
> > announcements channel
> 
> What kind of channel do you mean?
> 
> > `rm /var/www/pelican/app/Filament/Clusters/Settings.php`
> 
> Ok without this file it works

Good to hear. Make sure you close

**Comment by Tealk** [comment]
> The announcements channel in the Pelican server. Look at this message link -> https://discord.com/channels/1218730176297439332/1218753783786639380/1269714875173703831

Ok, I don't have Discord and I don't want to use it. I've also opened a [discussion ](https://github.com/pelican-dev/panel/discussions/526)about it.
