### ISSUE TITLE
composer.lock outdated

### ISSUE THREAD

**Issue by mark-boute** [pelican-dev/panel#533]
### Current Behavior

When following the Get Started documentation and running `composer install` I get the following output:

`Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run composer update or composer update <package name>.`

This does not matter when building on Ubuntu, but I am trying to build a NixOS derivation using `php83.buildComposerProject`. That requires the .lock file to be up-to-date unless I set the `composerStrictValidation = true;` option, which is not recommended for published packages.

### Expected Behavior

I expect the composer.json and .lock files to be in sync.

### Steps to Reproduce

Follow the Getting Started guide

### Panel Version

v1.0.0-beta7

### Wings Version

n.a.

### Error Logs

```bash
pelican@boisserver:/var/www/pelican$ composer validate
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
# Lock file errors
- The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
# General warnings
- No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Silver-Golden** [comment]
@mark-boute by any chance did ye get it to work nicely on nixos?   
If so do ye have a config ye can share?

**Comment by mark-boute** [comment]
> @mark-boute by any chance did ye get it to work nicely on nixos?   
> If so do ye have a config ye can share?

Semi-working. 
We managed to get it to build by changing a setting to not evaluate the lockfile, but decided to install the panel manually as it's essentially just a webpage.
We did get wings working. I think the repo is now private, so I'll check for relevant code real quick.

**Comment by mark-boute** [comment]
```
{ inputs, pkgs, lib, config, ... }:

with lib; let
  cfg = config.modules.pelican-panel;
  dir = "/var/www/pelican";
in {
  options = {
    modules.pelican-panel = {
      enable = mkEnableOption "Pelican Panel";
    };
  };

  config = mkIf cfg.enable {
    environment.systemPackages = [
      pkgs.curl
      pkgs.gnutar
      pkgs.unzip
      pkgs.php83
      pkgs.php83Packages.composer
      pkgs.php83Extensions.gd
      pkgs.php83Extensions.mysqli
      pkgs.php83Extensions.mbstring
      pkgs.php83Extensions.bcmath
      pkgs.php83Extensions.xml
      pkgs.php83Extensions.curl
      pkgs.php83Extensions.zip
      pkgs.php83Extensions.intl
      pkgs.php83Extensions.sqlite3
      ( import ./pelican-install.nix { inherit pkgs; inherit dir; } )
      ( import ./pelican-update.nix { inherit pkgs; inherit dir; } )
    ];

    systemd.timers."pelican-cron" = {
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnBootSec = "5m";
        OnUnitActiveSec = "1m";
        Unit = "pelican-cron.service";
      };
    };

    systemd.services."pelican-cron" = {
      script = ''
        ${pkgs.php83}/bin/php ${dir}/artisan schedule:run >> /dev/null 2>&1
      '';
      serviceConfig = {
        Type = "oneshot";
      };
    };

    systemd.services.pelican-queue = {
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
          User = "nginx";
          Group = "nginx";
          Restart = "always";
          ExecStart = "${pkgs.php83}/bin/php ${dir}/artisan queue:work --tries=3";
          startLimitInterval = 180;
          startLimitBurst = 30;
          RestartSec = "5";
      };
    };
  };
}```

**Comment by Silver-Golden** [comment]
That's amazing! 
by any chance do ye also have the ``pelican-update.nix`` ? I see it referenced above.

I honestly thought the wings would have been harder to make work than that

**Comment by matthijsk16** [comment]
Update script 
```nix
{ pkgs, dir }:

pkgs.writeShellScriptBin "pelican-update" ''
  DIR=${dir}
  
  echo "Updateing Pelican panel in $DIR ..."
  if [ -d $DIR ]; then
    echo "Directory $DIR found, entering maintenance mode ..."
  else
    echo "Directory $DIR does not exist, exiting"
    exit 1
  fi
  
  cd $DIR
  php artisan down

  echo "Downloading Pelican panel update ..."
  curl -L https://github.com/pelican-dev/panel/releases/latest/download/panel.tar.gz | tar -xzv

  echo "Setting permissions ..."
  chmod -R 755 storage/* bootstrap/cache

  echo "Updating Pelican panel using composer ..."
  yes | composer install --no-dev --optimize-autoloader

  echo "Clearing compiled template cache ..."
  php artisan view:clear
  php artisan config:clear 

  echo "Optimizing Pelican panel ..."
  php artisan filament:optimize

  echo "Updating the database ..."
  php artisan migrate --seed --force

  echo "Setting permissions ..."
  chown -R nginx:nginx $DIR

  echo "Restart Pelican queue service ..."
  systemctl restart pelican-queue.service

  echo "Exiting maintenance mode ..."
  php artisan up

  echo "Pelican panel updated successfully"
''
```

I want to add an important disclaimer for both the install and update script: 
Since Pelican is in beta, the install/update process can change with a new update. Therefore always first check the Pelican docs and change the above script before executing it. 

Also, if you ever come across a way to install Pelican the full nix way, please let us know!

**Comment by RMartinOscar** [comment]
Please make a PR.
