### ISSUE TITLE
Allocation are deleted, when you delete a Server

### ISSUE THREAD

**Issue by gOOvER** [pelican-dev/panel#541]
### Current Behavior

If you delete an existing server, the allocated ports in the node are also deleted

### Expected Behavior

The allocated ports in the node should not be deleted, but released

### Steps to Reproduce

- add allocated ports; p.e 27001-27005
- create a server with these ports
- delete the server
- check node allocated ports

### Panel Version

1.0.0-beta7

### Wings Version

1.0.0-beta3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
https://github.com/pelican-dev/panel/blob/main/app/Services/Servers/ServerDeletionService.php#L80

It shouldn't delete it
What's your Database driver ?

**Comment by gOOvER** [comment]
> https://github.com/pelican-dev/panel/blob/main/app/Services/Servers/ServerDeletionService.php#L80
> 
> It shouldn't delete it What's your Database driver ?

sqlite

**Comment by RMartinOscar** [comment]
Could it be this ?

https://github.com/pelican-dev/panel/blob/10806d6d6bcad8a875bdfc7fec7ecce2c6bced6c/database/migrations/2024_07_12_095213_fix_missing_sqlite_foreign_keys.php#L161

Im trying my best but im not at home rn

**Comment by gOOvER** [comment]
Before delete:
Pelican:
![MoQgYW](https://github.com/user-attachments/assets/49d67a13-13a3-477c-b4f5-d4e84ba7d416)

Pelican sqlite.db:
![bthETk](https://github.com/user-attachments/assets/3f4fcbf6-be26-4fb2-8b58-172cda9d1f51)

After delete:
Pelican:
![AbUe45](https://github.com/user-attachments/assets/a4773f0a-38f8-4353-9d30-fef083e6f10c)

sqlite.db:
![5vGkY0](https://github.com/user-attachments/assets/6811331c-e451-411d-a32b-d813743fa601)
