### ISSUE TITLE
Wings Error

### ISSUE THREAD

**Issue by Sterile-Gaming** [pelican-dev/panel#550]
### Current Behavior

root@ThunderHosting:~# systemctl status wings
● wings.service - Wings Daemon
     Loaded: loaded (/etc/systemd/system/wings.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-08-15 15:54:59 IST; 1h 15min ago
   Main PID: 4873 (wings)
      Tasks: 20 (limit: 76981)
     Memory: 647.3M
        CPU: 40.121s
     CGroup: /system.slice/wings.service
             └─4873 /usr/local/bin/wings

Aug 15 17:06:03 ThunderHosting wings[4873]:         github.com/pelican-dev/wings/server/power.go:174
Aug 15 17:06:03 ThunderHosting wings[4873]: github.com/pelican-dev/wings/server.(*Server).HandlePowerAction
Aug 15 17:06:03 ThunderHosting wings[4873]:         github.com/pelican-dev/wings/server/power.go:131
Aug 15 17:06:03 ThunderHosting wings[4873]: github.com/pelican-dev/wings/router/websocket.(*Handler).HandleInbound
Aug 15 17:06:03 ThunderHosting wings[4873]:         github.com/pelican-dev/wings/router/websocket/websocket.go:363
Aug 15 17:06:03 ThunderHosting wings[4873]: github.com/pelican-dev/wings/router.getServerWebsocket.func3
Aug 15 17:06:03 ThunderHosting wings[4873]:         github.com/pelican-dev/wings/router/router_server_ws.go:85
Aug 15 17:06:03 ThunderHosting wings[4873]: runtime.goexit
Aug 15 17:06:03 ThunderHosting wings[4873]:         runtime/asm_amd64.s:1650
Aug 15 17:06:03 ThunderHosting wings[4873]: unable to sync server data from Panel instance

### Expected Behavior

.. and i get banned from the server without any reason id - sterilegaming

### Steps to Reproduce

.. Opening panel then server and start

### Panel Version

1.0.0-beta7

### Wings Version

1.0.0-beta3

### Games and/or Eggs Affected

velocity

### Error Logs

```bash
https://paste.pelistuff.com/rH3X
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
You changed the Unit Prefix. This issue has been fixed and will be released with the next beta version. You can change it back to Binary Prefix, or replace your local file with the new one 

https://github.com/pelican-dev/panel/blob/main/app/Services/Servers/ServerConfigurationStructureService.php

You were banned for one day, with the reason of `please do not spam mention tags for attention and have patience please`
