### ISSUE TITLE
Panel mail settings has username as a mandatory field

### ISSUE THREAD

**Issue by Gr4Ss** [pelican-dev/panel#564]
### Current Behavior

When setting up an SMTP Servers via the panel interface, the 'Username' is a mandatory field.

Filling in a username in this case will allow the config to be saved but causes errors when trying to send a (test) mail.

### Expected Behavior

Username to be optional in case the mail server requires no authentication

By editing the .env file directly, it is possible to leave the username/password blank and get a working mail config for mail servers that require no username/password.

### Steps to Reproduce

1. Go to https://panel.example.com/admin/settings?tab=-mail-tab
2. Fill in the from address, from name, host and port
3. Leave the username and password fields empty
4. Click 'Save'

### Panel Version

1.0.0-beta8

### Wings Version

n/a

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Hey setting up mails without any user/password or certificate screams **bad practice !**
You shouldn't ever do that so i doubt The Pelican Team will ever make those fields optional.

**Comment by Gr4Ss** [comment]
There are legit reasons where you might want to use unauthenticated SMTP, e.g. when using postfix on localhost to forward the mails. Or OPNSense's postfix plugin doesn't even support user authentication currently...

It isn't like a mail server without authentication immediately means there is a mail server sitting open to the internet.
