### ISSUE TITLE
Favicon do not change on the default Dashboard Page.

### ISSUE THREAD

**Issue by Aenoxic** [pelican-dev/panel#568]
### Current Behavior

If you set a new favicon in the settings, it is updated in the admin area, but not on the dashboard page.

### Expected Behavior

The favicon should be displayed correctly on all pages.

### Steps to Reproduce

- Go to the "Settings" Page in the Admin Area
- Choose a new favicon
- Click "Save"
- Go to your main dashboard site

### Panel Version

1.0.0-beta8

### Wings Version

v1.0.0-beta4

### Games and/or Eggs Affected

None

### Docker Image

None

### Error Logs

```bash
No log required.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
The favicon only applies to Filament pages, so currently only the admin area.
When the client area will be converted too it will be "fixed".
