### ISSUE TITLE
Getting Timeout on Console Page

### ISSUE THREAD

**Issue by julian-piehl** [pelican-dev/panel#574]
### Current Behavior

Sometimes when I open a console page or reload it, the loading bar on top twitches extremely and after some time nothing loads anymore because pelican gave me a timeout.
I'm still able to access the admin page.

![image](https://github.com/user-attachments/assets/d407b911-b20d-49a8-90f6-0c8e67afdfbd)

In DevTools it looks like the UI is trying to start a websocket connection many times in a row (every request succeeds).

A screenshot of the DevTools Network Tab will follow as soon as I'm not in a timeout anymore and can access my console again...

### Expected Behavior

I don't want to get a timeout from just opening the page or pressing F5 one or two times.

### Steps to Reproduce

Open the pelican start page (not admin page) and select a server. Maybe press F5 or something.

### Panel Version

1.0.0-beta8

### Wings Version

1.0.0-beta4

### Games and/or Eggs Affected

Satisfactory

### Docker Image

ghcr.io/parkervcp/steamcmd:debian

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by parkervcp** [comment]
get the panel logs please.
`tail -n 150 /var/www/pelican/storage/logs/laravel-$(date +%F).log | curl -X POST -F 'c=@-' paste.pelistuff.com`

**Comment by julian-piehl** [comment]
https://paste.pelistuff.com/SdsY
![image](https://github.com/user-attachments/assets/861afcbd-59a9-4455-9b5f-f9c85e8e1163)

**Comment by notAreYouScared** [comment]
Created too far in the past. If I remember correctly the issue with that was your timezones are mixed.

**Comment by julian-piehl** [comment]
Thought the same and checked it.
My computer, the server and the config (.env file) all have the same timezone.

**Comment by julian-piehl** [comment]
**Update:** My Wings had the wrong timezone configured in `/etc/pelican/config.yml`. Let's see if the error still persists or if that was the fix.

**Comment by Boy132** [comment]
Either way this is not a bug but a configuration issue.
Next time please actually visit the Discord first and don't mindlessly tick off boxes.

**Comment by julian-piehl** [comment]
Oh, sorry for not responding anymore. The panel is now working as intended, so I forgot about it 😅


> Either way this is not a bug but a configuration issue. Next time please actually visit the Discord first and don't mindlessly tick off boxes.

Yes, this was a configuration issue **resulting in a bug**. If you have the timezone configured wrong, the panel shouldn't just make 50 requests in a row and get you in a timeout. Instead, a warning in the admin view, that the node has a different timezone than the Panel would be nicer instead of "You must be a hacker, we're going to send you into timeout". 😉
