### ISSUE TITLE
500 error when trying to login for the first time

### ISSUE THREAD

**Issue by ash-development** [pelican-dev/panel#577]
### Current Behavior

after running the installer (creating my account) i get a 500 error lightbox popup

### Expected Behavior

it should let me into my account and therefore the panel

### Steps to Reproduce

install the panel brand new and go to login

running `chmod -R 777 *` in `/var/www/pelican` does fix it, although i do not believe this is the most effective solution.

### Panel Version

v1.0.0-beta8

### Wings Version

n/a

### Games and/or Eggs Affected

n/a

### Docker Image

n/a

### Error Logs

```bash
https://paste.pelistuff.com/tEej
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ash-development** [comment]
ik this may be an issue for the docs repo, but wasn't 100% sure which to put it in lol

**Comment by Boy132** [comment]
You had wrong file permissions. The docs cover how to set correct permissions, e.g. `chown -R www-data:www-data /var/www/pelican` and `chmod -R 755 /var/www/pelican/storage/* /var/www/pelican/bootstrap/cache/`

Next time please visit the Discord first and don't mindlessly tick off boxes.
