### ISSUE TITLE
Copy wings configuration file button on panel does not copy in a valid format

### ISSUE THREAD

**Issue by ash-development** [pelican-dev/panel#578]
### Current Behavior

when copying the configuration file for wings in the panel, it pastes all in one line, which is not valid formatting & makes wings error out

### Expected Behavior

it should copy the full file, formatted in lines

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/b4945381-3567-4a7b-970b-c8e3a1707217)

### Panel Version

v1.0.0-beta8

### Wings Version

v1.0.0-beta4

### Games and/or Eggs Affected

n/a

### Docker Image

n/a

### Error Logs

```bash
root@ASHubuntu:/# sudo wings --debug
2024/09/15 18:14:34 cmd/root: error while reading configuration file: yaml: mapping values are not allowed in this context
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Copy works fine for me. Can you please try to reproduce it on the [demo](https://pelican.pterostuff.com/admin/nodes/1/edit?tab=-configuration-file-tab)?

**Comment by ash-development** [comment]
Ah seems to work now - not sure what was up with that.
