### ISSUE TITLE
Admin Role Users Without Permission Can Change Primary Allocation

### ISSUE THREAD

**Issue by FordCorn** [pelican-dev/panel#600]
### Current Behavior

Users given an admin role that only allows servers to be viewed are still able to change the primary allocation even without permission.

Extra info:  the user itself is also not able to add, remove, or modify current allocations on the server either, only view.

### Expected Behavior

The user should not be able to change the default allocation without the permission to change allocations on a server.

### Steps to Reproduce

Create a user role in the admin panel and give it server view permissions, log in as said user and look at the servers page, the user is able to change the primary allocation even though they do not have the required permissions to do so, or if this is even intended.

### Panel Version

1.0.0-beta10

### Wings Version

1.0.0-beta5

### Games and/or Eggs Affected

Minecraft (Fabric)

### Docker Image

ghcr.io/parkervcp/yolks:java_21

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Hey should be fixed with https://github.com/pelican-dev/panel/pull/601 thanks for your report !
