### ISSUE TITLE
Error 500 after updating panel on admin page

### ISSUE THREAD

**Issue by wolfslab** [pelican-dev/panel#602]
### Current Behavior

After following the guide on how to update the panel on the pelican dev website, when I go to the admin tab, it now says error 500 on it. Wings seems to be operational. I even updated it following the guide as well in case, but no luck. My servers are still running even after rebooting the whole Ubuntu VM its hosted in. The dev website says to also try to run `tail -n 100 /var/www/pelican/storage/logs/laravel-$(date +%F).log | grep "\[$(date +%Y)"`. But I get no output. So I try `chmod -R 755 /var/www/pelican/storage/* /var/www/pelican/bootstrap/cache/` as it said with no difference. 

### Expected Behavior

Its supposed to not give error 500 and let me access the admin portion of the panel. 

### Steps to Reproduce

Update the panel from (approximately) v1.0.0-beta4 to the latest using the instructions provided. 

### Panel Version

v1.0.0-beta10

### Wings Version

Latest version (unknown)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Please actually visit the Discord and don't just tick boxes.
Your answer was posted in the announcement channel.

**Comment by BonzTM** [comment]
> Please actually visit the Discord and don't just tick boxes. Your answer was posted in the announcement channel.

This was actually unhelpful reply.  The announcement issue was not the same as this one. 

@wolfslab [hopefully this fixes your issue](https://discord.com/channels/1218730176297439332/1297020173965852753/1297020173965852753) as it did mine.
``` shell
rm /var/www/pelican/app/Filament/Clusters/Settings.php
```

**Comment by Boy132** [comment]
> > Please actually visit the Discord and don't just tick boxes. Your answer was posted in the announcement channel.
> 
> This was actually unhelpful reply. The announcement issue was not the same as this one.
> 
> @wolfslab [hopefully this fixes your issue](https://discord.com/channels/1218730176297439332/1297020173965852753/1297020173965852753) as it did mine.
> 
> ```shell
> rm /var/www/pelican/app/Filament/Clusters/Settings.php
> ```

You just have to look at the right announcement: https://discord.com/channels/1218730176297439332/1218753783786639380/1269714875173703831
