### ISSUE TITLE
Add DB migration step to documentation

### ISSUE THREAD

**Issue by joejoepie** [pelican-dev/panel#603]
### Current Behavior

The basic documentation doesn't include a step to run the database migration.

### Expected Behavior

It should probably include it.

### Steps to Reproduce

While installing the Pelican panel using the documentation on the website, I ran into the issue when trying to launch the web installer that the sqlite database didn't exist yet. As far as i notice there is no current documentation in the basic steps that tell you you should run the artisan migrate script. This issue is to make the project owners aware of this, unless I'm wrong of course, in which case i apologize for the time wasted reading this text!

### Panel Version

1.0.0-beta10

### Wings Version

1.0.0-beta5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
No, that's normal. The web installer will run migrations for you.
These errors about the database file from the logs are from the queue worker. Because it's setup before the web installer part.

**Comment by joejoepie** [comment]
Just want to add that I indeed started the queue worker first, but navigating to the installer (/installer path) provided me with an HTTP 500 error. The logs than clearly showed that this exact issue was due to the sqlite file not existing. Not sure if I did a step out of order, but running migration fixed this issue.

**Comment by Shadowfita** [comment]
> Just want to add that I indeed started the queue worker first, but navigating to the installer (/installer path) provided me with an HTTP 500 error. The logs than clearly showed that this exact issue was due to the sqlite file not existing. Not sure if I did a step out of order, but running migration fixed this issue.

I had the same issue. Seemed like nothing was running migrations in the set-up process.
