### ISSUE TITLE
Schedules running at 2 different times.

### ISSUE THREAD

**Issue by BrianDLC** [pelican-dev/panel#605]
### Current Behavior

Schedules seem to run twice at two different times, today I was able to notice all schedules run at other times, I had set up an alarm to run every 3 hours, another to run at 0 0 * * * and another to run at */3, which would be every 3 hours, all 3 ran at the same time at 0 UTC. The 0 0 * * * schedule ran at 4PM and again at 8PM (it should run at 8PM), after it ran again at 8PM, it claims the next scheduled run time is at 4PM, meaning it'll most likely run at 4PM and 8PM again the next day. I did have this issue a month ago and had more information but decided to turn off all schedules due to wanting to progress on a game server.

The issue persists, If I run a schedule it will run at the time I designated and at another time around 4 hours before the scheduled time. I do not understand how to troubleshoot this and would love some assistance.

I've even tried updating the panel as well as setting the schedule on another server and node, still same issue, seems to have started happening after some time using the panel as it did work for a time.

### Expected Behavior

Schedules should run as intended by the cron schedule

### Steps to Reproduce

Create any schedule and see when it runs.

### Panel Version

1.0.0-beta10

### Wings Version

1.0.0-beta4

### Games and/or Eggs Affected

All (Testing on Minecraft Neoforge)

### Error Logs

```bash
https://paste.pelistuff.com/anwT panel
https://paste.pelistuff.com/tjbX wing 1
https://paste.pelistuff.com/3BFF wing 2
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Make sure your [contab](https://pelican.dev/docs/panel/panel-setup#crontab-configuration) and [queue worker](https://pelican.dev/docs/panel/panel-setup#setting-up-queue-service) are setup correctly. Also make sure that there aren't multiple queue workers running. The queue worker was previously called `pelicanq` or just `pelican`, it should now be called `pelican-queue`.

Also note that the schedule cron time (e.g. `0 0 * * *`) is _always_ displayed as UTC while `Next run` and `Last run` are displayed in your timezone. Just mentioning it to make sure there are no confusions.

**Comment by Boy132** [comment]
Did you change the `APP_TIMEZONE` in your database? It should be set to `UTC`.

**Comment by BrianDLC** [comment]
No as I have not made any additional changes to the config outside of the panel GUI, as in, after setting up the panel/nodes after following the guide on the pelican panel docs I made no other changes to them.

**Comment by Boy132** [comment]
Please try the changes from [here](https://github.com/pelican-dev/panel/compare/main...Boy132:pelican-panel:fix/schedule-timezones) and see if the problem still occurs.

**Comment by BrianDLC** [comment]
Alright I've made the changes, will set up some schedules to test.

**Comment by Boy132** [comment]
@BrianDLC Were you able to test the changes? Is the issue still occurring?

**Comment by BrianDLC** [comment]
After testing, I would have to say that this change did resolve the issue, thanks!
________________________________
