### ISSUE TITLE
Deleting a newly-set primary allocation on a server

### ISSUE THREAD

**Issue by JustNotSebas** [pelican-dev/panel#609]
### Current Behavior

Discovered this on total accident, but when having an allocation selected on the server edit page, and setting that allocation as primary, it **doesn't** remove the selection (still appears as 1 record selected even though the checkmark dissapeared), and it allows to dissociate all the allocations on the server, including the primary one, which isn't supposed to be deleted.
![image](https://github.com/user-attachments/assets/8a247ddd-c818-4353-9579-fa9b554849a7)
![image](https://github.com/user-attachments/assets/d610e81d-0663-47ce-a712-53d41c98eae5)

It also makes the address show as "n/a" on the user page.
![image](https://github.com/user-attachments/assets/cb5bd35d-cd18-457e-99f2-a6b7818da8bf)

It's not that big of a deal, because you can set back the allocation on the server page, but being that it happened to me by accident, it's best to have it solved to avoid issues.

### Expected Behavior

When clicking on "Make Primary", it should remove the selection, or at the very least, have a warning if the user attempts to delete the primary allocation of the server.

### Steps to Reproduce

Prerrequisite: Have at least two allocations on the server, one being the primary one.

1. Select the non-primary allocation, being the only one that _can_ be selected.
2. With the allocation selected, click "Make Primary"

The allocation will remain selected, even though the checkmark dissapeared.

- From this point, you can dissociate the allocation, or both of them. Doing this will result on the server losing it's primary allocation.

### Panel Version

1.0.0-beta10

### Wings Version

1.0.0-beta4

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
I think think this would be a filament bug as that's all handled by it and it's packages.
