### ISSUE TITLE
Role permissions "Servers"

### ISSUE THREAD

**Issue by XdelaDiscord** [pelican-dev/panel#634]
### Current Behavior

When the user has permission to see the server list he does not have the "SHOWING OTHERS' SERVERS" button to see the list of other servers on the panel. I don't know if it's a bug or an oversight.

### Expected Behavior

The "SHOWING OTHERS' SERVERS" button is displayed when you are on the panel in client mode and have permission

### Steps to Reproduce

1. create a role with server permissions
2. add the role to a third party
3. check with this person that they have the "SHOWING OTHERS' SERVERS" button

### Panel Version

Version: 1.0.0-beta10

### Wings Version

wings v1.0.0-beta5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Hey the Role Permissions are only effective for the admin area at this time, it will be good when #416 will get merged.
The current client area still uses the legacy permission system.
