### ISSUE TITLE
App_name can contain special characters in the installer, but not in the settings page.

### ISSUE THREAD

**Issue by GaspardG0001** [pelican-dev/panel#644]
### Current Behavior

When configuring the name displayed in the installer, it is possible to use special characters (space, _, -, ...). However, when modifying the panel parameter page, this returned an error due to the use of characters other than numbers and letters.

### Expected Behavior

The two elements need to be made coherent: 
- It is not possible to use special characters.
- It is possible to use these special characters.

### Steps to Reproduce

Try to configure a name with special characters in the installer. Try to modify in parameters .

### Panel Version

1.0.0-beta10

### Wings Version

none

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
This will already be fixed in the next release.
