### ISSUE TITLE
Remove stock eggs (json files) and download json urls instead

### ISSUE THREAD

**Issue by Boy132** [pelican-dev/panel#649]
Instead of shipping egg jsons directly with the panel we should just import egg urls when seeding.
This requires to add the current stock eggs to the egg repos first if they are missing there.

Example: _(pseudo code)_
```php
$importer = app(EggImporterService::class);
$importer->fromUrl('https://raw.githubusercontent.com/pelican-eggs/minecraft/refs/heads/main/java/vanilla/egg-vanilla.json');
$importer->fromUrl('https://raw.githubusercontent.com/pelican-eggs/minecraft/refs/heads/main/java/paper/egg-paper.json');
$importer->fromUrl('https://raw.githubusercontent.com/pelican-eggs/minecraft/refs/heads/main/java/forge/egg-forge.json');
$importer->fromUrl('https://raw.githubusercontent.com/pelican-eggs/games-steamcmd/refs/heads/main/gmod/egg-gmod.json');
$importer->fromUrl('https://raw.githubusercontent.com/pelican-eggs/games-steamcmd/refs/heads/main/rust/egg-rust.json');
```

We could maybe also include a egg import step to the installer, so you can choose which eggs to import (from a predefined selection and info where to get more eggs).

**Comment by lancepioch** [comment]
This is going to be a whole separate thing as part of the Pelican Hub.

I'll make the appropriate issues and pull requests when it's time!

For now, some tests rely on these eggs being there, so we're kind of stuck with them for now.
