### ISSUE TITLE
Associate Port

### ISSUE THREAD

**Issue by MonsPropre** [pelican-dev/panel#663]
### Current Behavior

When you try associate port to an existing server in the admin dashboard and search by port it return (no result) cuz the request search port but the available entry is only ip

### Expected Behavior

Typing for example 34034 to select a port instead of need type 127.0.0.1 to allocate the port (ip:port didn't work too)
Actually i can only search by ip and not by port

### Steps to Reproduce

1. Go on ur panel: `https://manage.domain.tld/admin/servers/4/edit?tab=-mounts-tab`
2. Click on `Add Allocation`
3. Type port like `34034` and try `ip:34034` too (is an example port)

### Panel Version

1.0.0-beta10

### Wings Version

wings v1.0.0-beta5

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Hey this is a duplicate of https://github.com/pelican-dev/panel/issues/408
And will be fixed with https://github.com/pelican-dev/panel/pull/395

**Comment by MonsPropre** [comment]
> Hey this is a duplicate of #408 And will be fixed with #395

oh my bad i didn't see this one, thx

**Comment by RMartinOscar** [comment]
Could you close it as `not planned` instead please ?
