### ISSUE TITLE
Change the images via dropdown, does not take over the image

### ISSUE THREAD

**Issue by gOOvER** [pelican-dev/panel#672]
### Current Behavior

If you want to change the image via the dropdown in a server (admin area), the image is not set correctly in the “Image” field.

See video

### Expected Behavior

Image should be changed during selection

### Steps to Reproduce

add more than 1 image to egg and try to change it in Server (Admin Area)

### Panel Version

1.0.0-beta11

### Wings Version

v1.0.0-beta6

### Games and/or Eggs Affected

every

### Docker Image

every

### Error Logs

```bash
https://zipline.gameserver.tech/u/oFfub2.mp4
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
If you're delete the value in the text box, then change it. What happens? 

How it should work
If you have custom image selected in the drop down the value of the text box is used. If you use an option from the drop down, that value will be used. It's not suppose to change the text box.

**Comment by gOOvER** [comment]
> If you're delete the value in the text box, then change it. What happens?

https://[zipline.gameserver.tech/u/j8YNBP.mp4](https://zipline.gameserver.tech/u/j8YNBP.mp4)
 
> How it should work If you have custom image selected in the drop down the value of the text box is used. If you use an option from the drop down, that value will be used. It's not suppose to change the text box.

But this is very confusing, because the correct image should already be displayed
