### ISSUE TITLE
File Manager opens non-existing file

### ISSUE THREAD

**Issue by RMartinOscar** [pelican-dev/panel#678]
### Current Behavior

![image](https://github.com/user-attachments/assets/47752270-8be1-472a-ae56-dfe9f3ea85cb)
![image](https://github.com/user-attachments/assets/2f31d093-a3be-47e1-91c4-9f4d427a7821)

Access the file like we wanted to create it

### Expected Behavior

Throws equivalent of 404

### Steps to Reproduce

Go to FileManager create a new file save it then edit the url to something that doesn't exists and voilà !

### Panel Version

1.0.0-beta11

### Wings Version

1.0.0-beta6 (not relevent)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
No point in changing this, as the old client area will be replaced. Try to reproduce it on the client area branch, if you can update the issue.

**Comment by RMartinOscar** [comment]
> No point in changing this, as the old client area will be replaced. Try to reproduce it on the client area branch, if you can update the issue.

Well good news i could reproduce it in the new area (updated images)

**Comment by Boy132** [comment]
We will wait for https://github.com/pelican-dev/wings/issues/48 and then fix it in the new client area.
