### ISSUE TITLE
User Suspension

### ISSUE THREAD

**Issue by lancepioch** [pelican-dev/panel#70]
### Discussed in https://github.com/pelican-dev/panel/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **martinbndr** April 12, 2024</sup>
Being able to suspend users in pelican panel.
Users suspended should be completly logged out and won´t be able to login anymore. Specific error message will show that.
Please also add api support for that.</div>

**Comment by Googletod12355** [comment]
I can agree, right now there is no way to stop certain users from remaking their account

**Comment by Poseidon281** [comment]
Working on it.
