### ISSUE TITLE
checking the wrong version number

### ISSUE THREAD

**Issue by Tealk** [pelican-dev/panel#711]
### Current Behavior

The wrong version number is checked in the nodes, namely that of the panel instead of wings

![image](https://github.com/user-attachments/assets/5f6d9da8-c0ec-45b6-8284-954b642e9ff8)

### Expected Behavior

The current wings number is displayed.

### Steps to Reproduce

Open notes settings

### Panel Version

1.0.0-beta13 

### Wings Version

1.0.0-beta7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Already fixed with #709 and will be included in the next beta.

**Comment by Tealk** [comment]
That confuses me @Boy132 , the change says that wings will be changed to panel, which is exactly the wrong way around? The version number of wings should be there.

**Comment by Boy132** [comment]
The panel version used the cache key name for wings. So the cache for the panel version was overwritting the cached wings version.
That's why the panel version is displayed, and #709 fixed that.
