### ISSUE TITLE
Wrong version of wings displayed in nodes

### ISSUE THREAD

**Issue by GaspardG0001** [pelican-dev/panel#719]
### Current Behavior

The latest version of wings displayed on a node's summary page is not the correct version (1.0.0-beta13 ).

### Expected Behavior

The latest version of wings displayed on a node's summary page should be (1.0.0-beta7 ).

### Steps to Reproduce

Go to the node summary page and check the latest version of Wings indicated.

### Panel Version

1.0.0-beta13

### Wings Version

1.0.0-beta7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Duplicate and patched in the next release
