### ISSUE TITLE
Orderable/Sortable/Draggable Egg Variables

### ISSUE THREAD

**Issue by lancepioch** [pelican-dev/panel#72]
### Discussed in https://github.com/pelican-dev/panel/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **HerrSammyDE** April 13, 2024</sup>
Currently the egg variables are all created one after the other, but I would very much like to be able to sort / move the variables, so a function to move them would be very good and helpful</div>

**Comment by QuintenQVD0** [comment]
Yes indeed good idea, As for now the variables get the order they where made and can be a little confusing from egg to egg.
So a sort or a way to organize them (just fine if it are just the ones the user can see) would be nice.
