### ISSUE TITLE
Any username that is < 3 characters throws a 500 error.

### ISSUE THREAD

**Issue by jackh54** [pelican-dev/panel#729]
### Current Behavior

When creating a new user in the panel, if their username is less than 1 or 2 characters it throws a 500 error.

### Expected Behavior

Instead of a giant 500 error flashing in my face, put a small popup that says usernames should be greater than 2 characters and contain only letters.

### Steps to Reproduce

Create a user in /admin/users, then create a test user with only 1 or 2 characters in the username.

### Panel Version

1.0.0-beta13

### Wings Version

v1.0.0-beta7

### Games and/or Eggs Affected

n/a

### Docker Image

n/a

### Error Logs

```bash
https://paste.pelistuff.com/3cKn
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Thanks for your report
https://github.com/pelican-dev/panel/pull/730
