### ISSUE TITLE
Global Search w/ New Client Area

### ISSUE THREAD

**Issue by antho-444** [pelican-dev/panel#736]
### Current Behavior

When using the new Client Area, Attempting to use the global search feature will cause a 500 Server Error. 

### Expected Behavior

Using the global search feature is supposed to allow you to search a specific file or file type within the whole directory.

### Steps to Reproduce

1. Use New Client Area
2. Click on a server
3. Head over to Files Tab
4. Click Global Search
5. Type in query to search
6. 500 Server Error

### Panel Version

1.0.0-beta14

### Wings Version

1.0.0-beta7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Needs #44
