### ISSUE TITLE
Files Save is loading more

### ISSUE THREAD

**Issue by Bubbelwubbel** [pelican-dev/panel#743]
### Current Behavior

When I save a file, it loads indefinitely on the web page, but when you perform an action it stops.

### Expected Behavior

That it doesn't change.

### Steps to Reproduce

https://github.com/user-attachments/assets/c17041ac-84b0-4b0d-a15a-c5b50b1eef77

### Panel Version

canary (e5433b7)

### Wings Version

1.0.0-beta7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
Yeh, we have no idea what causes this...

**Comment by JustRed23** [comment]
After a bit of testing, this is caused by pressing ctrl + a and then deleting, my guess is that it is trying to delete something that it shouldnt. Also after this when you refresh your tab / go back and go to the file again, the text is not editable anymore until you shift + refresh

**Comment by notAreYouScared** [comment]
Going on a limb and saying this is an issue with the filament plugin we are using, Ill do some more testing when i get home and open a bug report on their repo if needed.
