### ISSUE TITLE
Not being able to add subusers if the subuser email is already on a account

### ISSUE THREAD

**Issue by dbcaa** [pelican-dev/panel#745]
### Current Behavior

When i try to add a subuser to a server if they're email is already on a pelican account it says `The email has already been taken.` Screenshot for more info
<img width="894" alt="Screenshot 2024-12-01 at 1 36 45 PM" src="https://github.com/user-attachments/assets/0ba351e8-19b4-494c-bcd2-4cda4472c7cc">

### Expected Behavior

When i add the subuser it should work fine and show the server in the users client area

### Steps to Reproduce

try and add a subuser to a server with a email that is already on a pelican account

### Panel Version

1.0.0-beta14

### Wings Version

1.0.0-beta7

### Games and/or Eggs Affected

None

### Docker Image

None

### Error Logs

```bash
Logs not found for panel
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Hey this is a known issue but thanks for your report.
