### ISSUE TITLE
Reload on Settings save

### ISSUE THREAD

**Issue by Leon-JavaScript** [pelican-dev/panel#773]
### Current Behavior

When clicking on the "Save" button in the admin settings tab, the browser asks you if you want to leave the page and changes don't get saved. I guess this doesn't make much sense, because in other parts (e.g. clicking on "Save" in eggs), this doesn't appear.
![image](https://github.com/user-attachments/assets/41df0450-de7e-4ffa-a383-3657a1483824)
_Browser: Google Chrome_

### Expected Behavior

The settings should just be saved and the prompt should not be there.

### Steps to Reproduce

1. Go to the settings in the admin area
2. Press on "Save"

### Panel Version

Tested on 1.0.0-beta14 and canary (b50acfd)

### Wings Version

1.0.0-beta7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Hey this is a well known behavior we are searching for a solution.
The problem is that when you hit save on egg it stores the result in database but when you save on the settings page those are stored in .env and as the panel depends on it you need to refresh the page on change.
