### ISSUE TITLE
New client area file size calculation is wrong

### ISSUE THREAD

**Issue by RubenRME** [pelican-dev/panel#779]
### Current Behavior

The file size listed is different between new and old client areas.

### Expected Behavior

The same file size listed is the same between new and old client areas.

### Steps to Reproduce

1. Have a big file in one of your servers (easier to observe I'd assume).
2. Observe the file size in old client area
![image](https://github.com/user-attachments/assets/d62d0cc6-54a8-42dc-8073-e66db6f635f7)
3. Observe the file size in the new area.
![image](https://github.com/user-attachments/assets/caa0c94f-0c4d-4b9c-8873-4d622f89837e)

File properties on windows:
![image](https://github.com/user-attachments/assets/dff69ddb-a16d-4df0-9708-e6eec406bc4e)

### Panel Version

1.0.0-beta14

### Wings Version

1.0.0-beta7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
Mind the unit. One is `GiB`, the other is `GB`.

And Windows uses `GiB` but shows it (wrongly) as `GB`.
