### ISSUE TITLE
Wrong theme when switching from admin panel to client panel

### ISSUE THREAD

**Issue by marl0nx** [pelican-dev/panel#786]
### Current Behavior

I selected the "new client panel theme" ending with "/app". When entering the admin panel and exiting again it uses the "old client panel theme"

### Expected Behavior

It should use the one you selected before.

### Steps to Reproduce

1. Change to "New Client Area"
![image](https://github.com/user-attachments/assets/d5fe4a36-0572-4ab9-9c2b-63271eb94cec)
2. Open Admin Panel
3. Leave Admin Panel

### Panel Version

v1.0.0-beta14

### Wings Version

v1.0.0-beta8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment]
That's correct. Currently the old client area is still the default.
