### ISSUE TITLE
SSL setting selection does not persist on validation error when creating a node

### ISSUE THREAD

**Issue by iamkubi** [pelican-dev/panel#8]
### Current Behavior

Create a new node in admin area.  Set SSL to use HTTP.  Forget to fill out over-allocation boxes and hit submit.  Get validation error saying over-allocation settings are missing.  Fill them in and hit submit, get validation error saying that fqdn cannot be an IP address while HTTPS is enabled.

This happens because the HTTPS setting resets on validation errors while other fields persist.

### Expected Behavior

HTTPS setting selection persists on validation errors

### Steps to Reproduce

Above

### Panel Version

v3

### Wings Version

main

### Error Logs

```bash
https://i.imgur.com/qdQTuAr.png
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment]
Should have been fixed with #401
