### ISSUE TITLE
Error 500 on the New Client Area

### ISSUE THREAD

**Issue by LostEtienne** [pelican-dev/panel#807]
### Current Behavior

When i was clicking around in the New Client Area, I noticed that the Page "Startup" on a Server resulted in an Error 500

### Expected Behavior

Just the normal, expected startup page to be shown

### Steps to Reproduce

Just click on Startup in the New Client Area

### Panel Version

1.0.0-beta16

### Wings Version

1.0.0-beta8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by gOOvER** [comment]
cant confirm. but idk, what you men with startup page. All pages working fine so far

**Comment by notAreYouScared** [comment]
Please Attach logs... Without them... we cannot help.

What Database Driver are you using? MySQL? MariaDB? SQLite?

If using MySQL/MariaDB, whats the server version?

**Comment by lancepioch** [comment]
You need to help us, help you.
