### ISSUE TITLE
PHP missing dependencies

### ISSUE THREAD

**Issue by iUnstable0** [pelican-dev/panel#812]
### Current Behavior

Currently, if you follow the getting started guide in the wiki, you wont be able to install composer dependencies as it will throw this error

missing extension ext-intl and ext-pdo_sqlite

so when you run artisan environment setup, it will throw cannot find file vendor/autoload.php because the dependencies are not installed.

The fix is to install php8.3-{sqlite3,intl}

### Expected Behavior

Expected package to successfully install

### Steps to Reproduce

Install these

apt -y install php8.3 php8.3-{common,cli,gd,mysql,mbstring,bcmath,xml,fpm,curl,zip}

Run the composer install on the wiki

```
$ COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader
Composer could not detect the root package (pelican-dev/panel) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires PHP extension ext-intl * but it is missing from your system. Install or enable PHP's intl extension.
  Problem 2
    - calebporzio/sushi is locked to version v2.5.2 and an update of this package was not requested.
    - calebporzio/sushi v2.5.2 requires ext-pdo_sqlite * -> it is missing from your system. Install or enable PHP's pdo_sqlite extension.
  Problem 3
    - filament/support is locked to version v3.2.124 and an update of this package was not requested.
    - filament/support v3.2.124 requires ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
  Problem 4
    - filament/widgets is locked to version v3.2.124 and an update of this package was not requested.
    - filament/support v3.2.124 requires ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
    - filament/widgets v3.2.124 requires filament/support v3.2.124 -> satisfiable by filament/support[v3.2.124].
```

### Panel Version

v1.0.0-beta16

### Wings Version

none

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by gOOvER** [comment]
Not an issue. Why dont you install it?
