### ISSUE TITLE
Missing edit function for actions on schedules in new client

### ISSUE THREAD

**Issue by e-monkey** [pelican-dev/panel#818]
### Current Behavior

If editing a schedule, there is no edit nor delete option for actions.

### Expected Behavior

Actions should be at least deletable, better editable.

### Steps to Reproduce

Edit a schedule on a server in new client console.

Example path: `/app/server/{id}/schedules/{id}/edit`

### Panel Version

1.0.0-beta16

### Wings Version

1.0.0-beta8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by e-monkey** [comment]
This is my very first issue I created on Github, so please bear with me and let me know if you have any suggestions to improve it.

I checked the existing issues, and I hope did not miss anything important.

**Comment by notAreYouScared** [comment]
You know... You're right.. I'll make a PR to add them. Thanks for the report :)
