### ISSUE TITLE
[New Client Area] Unable to remove sub-users if wings is not reachable.

### ISSUE THREAD

**Issue by notAreYouScared** [pelican-dev/panel#827]
Unable to remove subusers if wings is offline, guessing its failing on telling wings to invalidate the user, if wings is offline we should nuke the user in the panel.

**Comment by Boy132** [comment]
Should already be the case: https://github.com/pelican-dev/panel/blob/main/app/Services/Subusers/SubuserDeletionService.php#L35-L40

**Comment by notAreYouScared** [comment]
Nope throws a 500 due to failing to connect to wings, and the sub-user stays
