### ISSUE TITLE
New client area bug when viewing others servers

### ISSUE THREAD

**Issue by dbcaa** [pelican-dev/panel#835]
### Current Behavior

Although I have an admin role that has perms to view others servers when i click a server that isnt owned by me it shows a 404 not found.

### Expected Behavior

Expected is for me to be able to click the server and access it as normal

### Steps to Reproduce

Make an account with a admin role (Not root admin) a custom role that has perms to view others servers and try to click on someones server not owned by you

### Panel Version

1.0.0-beta16

### Wings Version

1.0.0-beta8

### Games and/or Eggs Affected

None

### Docker Image

None

### Error Logs

```bash
https://paste.pelistuff.com/TkPW
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by notAreYouScared** [comment]
This is known and will be addressed, thankyou for making an issue so its not forgotten about :)

**Comment by Boy132** [comment]
That's not a bug, it's intentional for now. The admin still has to be added as subuser.

#613 will also improve this.
